name: CI (local)

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, tokenizer, xml
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Ensure Sail executable
        run: chmod +x vendor/bin/sail

      - name: Start Sail
        run: ./vendor/bin/sail up -d

      - name: Wait for Laravel container to be ready
        run: |
          for i in {1..15}; do
            container_id=$(docker ps --filter "name=laravel.test" -q)
            if [ -z "$container_id" ]; then
              echo "laravel.test container not found"
            else
              status=$(docker inspect -f '{{.State.Running}}' "$container_id")
              if [ "$status" = "true" ]; then
                echo "laravel.test is running"
                break
              fi
            fi
            echo "Waiting for laravel.test container to be ready..."
            sleep 3
          done

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..15}; do
            ./vendor/bin/sail exec pgsql pg_isready -U "${DB_USERNAME:-postgres}" && break
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Prepare environment
        run: |
          ./vendor/bin/sail exec laravel.test cp .env.testing .env
          ./vendor/bin/sail artisan key:generate
          ./vendor/bin/sail artisan migrate --force

      - name: Run tests
        run: ./vendor/bin/sail test

      - name: Shut down Sail
        if: always()
        run: ./vendor/bin/sail down
