name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build app container
        run: |
          DOCKER_BUILDKIT=0 docker compose -f docker-compose.ci.yml build app

      - name: Start containers
        run: |
          docker compose -f docker-compose.ci.yml up -d

      - name: Wait for DB to be ready
        run: |
          for i in {1..15}; do
            docker compose -f docker-compose.ci.yml exec -T db pg_isready -U postgres && break
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Prepare Laravel application
        run: |
          docker compose -f docker-compose.ci.yml exec -T app cp .env.testing .env
          docker compose -f docker-compose.ci.yml exec -T app composer install --no-interaction --prefer-dist
          docker compose -f docker-compose.ci.yml exec -T app php artisan key:generate
          docker compose -f docker-compose.ci.yml exec -T app php artisan migrate --force

      - name: Run Laravel tests
        run: |
          docker compose -f docker-compose.ci.yml exec -T app php artisan test

      - name: Tear down containers
        if: always()
        run: docker compose -f docker-compose.ci.yml down --volumes --remove-orphans
